### ISSUE TITLE
Support for 2.0 (and newer versions in general)

### ISSUE THREAD

**Issue by RobertoMaurizzi** [dominicrodger/djohno#1]
Hi,

I'm starting to develop a new application "from scratch" on 2.0 and while searching for useful applications and libraries I've found djohno and, remembering what happened to me last time I had to set up this kind on functionality in another application, I decided to install it.

I'm trying to adapt it to 2.0 and it's been quite straightforward. After a few fixes, there's only one test that fails, but I can't exactly understand the rationale for the test and decide how/if I should 'port' it:

```
    def test_djohno_server_error_handler(self):
        """
        Tests to ensure our handler500 works correctly.
        """
        url = reverse('server_error_handler')
        response = self.client.get(url)
        self.assertEqual(response.status_code, 500)
        self.assertTrue('STATIC_URL' in response.context)
```
I'm having trouble with the check for STATIC_URL.

First of all, STATIC_URL is undefined in tests/settings.py. I can't remember if in the past it was automatically added, but right now it's None if you don't define it. This makes me wonder why there's a test for that, as it would test the tests' settings.py

Defining it however doesn't help much: Unless I've made a mistake in changing the Context to a simple dict (I was getting an error because of that in the test, but I quite remember that now a context is a simple dictionary) the response.context I get is a quite "strange" object: (a list of lists and dicts) that at a certain point contains a dict with STATIC_URL as a key... It looks like something that might change with some unrelated change in Django's template code.

If you can shed some light on this, I can finish committing the changes to my fork and send you a PR.

**Comment by RobertoMaurizzi** [comment]
Update: I actually didn't use a simple dictionary for Context as I thought -__-;
Now that I do, the test passes. I'm still not sure why it's tested, but I guess that at a certain point you had an error because it was missing or None.
Committing and sending the PR :-)

**Comment by dominicrodger** [comment]
Thanks for looking at this @RobertoMaurizzi - I'll close this issue, and take a look at the pull request.
